### ISSUE TITLE
Создание функции победы в игре (D2)

### ISSUE THREAD

**Issue by YuryNaumov** [YuryNaumov/CardGame2022#4]
### Создание функции победы в игре

Создать функцию, выполняющую рутину при победе в игре. Победа наступает только в том случае, если здоровье врага опустилось до нуля.

Необходимо выдать сообщение
> Поздравляем! **Имя_врага** повержен.

Выдержать небольшую паузу, возможно запустить какую-нибудь анимацию.

После чего игра перезапускается.

**Comment by dfoxs353** [comment]
Ефремов и Платов беремся за выполнение задачи
